# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b9ed84fc03aee530d108fe79eb924e37334a731da3404fd6f22c5b21f4ff9979c0361750fb6051a33c99ecbfaa0c7c3e3f7fa9e80cffdfd83558d774729f509

test:
  secret_key_base: a41292838e529bc66fc645e264dc3603b6ca4c2f578b66f94ccf16bfd52c0f9ad1bafa52e4059c5bce3b3f23abb0e50165f59fab9a62368e4777fda21b5ed574

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
